#! /bin/sh

#  _                                      
# | |__  ___ _ ____      ___ __  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_|_|  \___|
#           |_|                           

# Si existe el proceso sxhkd lo finaliza y luego lo inicia
pgrep -x sxhkd > /dev/null || sxhkd &

# Iniciar polybar
$HOME/.config/polybar/launch.sh

# Configurar fondo de pantalla con nitrogen
nitrogen --restore &

# Manejar transparencias con picom
/usr/local/bin/src/picom -f &

# fix for some Java apps
# Arregla algunas apps de java (como netbeans)
wmname LG3D &

# Crear el numero de escritorios o areas de trabajo (I II ...)
# bspc monitor -d I II III IV V VI VII VIII IX X
if xrandr -q | grep 'DP-1 connected'; then
    xrandr  --output eDP-1 --mode 1366x768 --output DP-1 --mode 1360x768
    --right-of eDP-1
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
    bspc monitor DP-1 -d X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi
# xrandr --output eDP-1 --mode 1366x768

bspc config border_width         3                          # Ancho del borde
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
